### ISSUE TITLE
JSDoc 4 support

### ISSUE THREAD

**Issue by rotsee** [clenemt/docdash#109]
Replace `taffydb` with `@jsdoc/salty` to support JSDoc 4.0.0. See detailed instructions here:

https://github.com/jsdoc/jsdoc/tree/main/packages/jsdoc-salty#use-salty-in-a-jsdoc-template

**Comment by Bugs5382** [comment]
@rotsee created a PR. I also tested it locally by modifying the files and it worked. So now just waiting for an official code merge.

**Comment by Bugs5382** [comment]
@ar2rsawseen please merge and publish :)
