### ISSUE TITLE
configure the theme

### ISSUE THREAD

**Issue by zhumj1** [clenemt/docdash#116]
Do you have the option to configure the theme?

**Comment by ar2rsawseen** [comment]
Hello,
there is a "scripts": [] option where you can provide list of js and CSS files to load and override default values

**Comment by zhumj1** [comment]
thank you

**Comment by xrui94** [comment]
How to use the "scripts" config item? Is there a example? This is my config below, but it is not working.

**Comment by ar2rsawseen** [comment]
Hello
The usage is correct, and I think the problem is the relative path to the file
If you look at the generated source code of the doc and find your script included there, what path does it have, and how is it relative to where your script actually is?

**Comment by xrui94** [comment]
> Hello The usage is correct, and I think the problem is the relative path to the file If you look at the generated source code of the doc and find your script included there, what path does it have, and how is it relative to where your script actually is?

Hi
Thank you for your reply! Yes, my usage is correct. It is indeed the relative path error of the css file. When the browser accesses the "common.css" file, the browser reports a 404 error. I move the "common.css" file to the styles folder of the api document directory, it can work normally

**Comment by ar2rsawseen** [comment]
Hello,
so just to confirm, the issue is resolved then? :)

**Comment by xrui94** [comment]
> Hello, so just to confirm, the issue is resolved then? :)

Yes，it is working.
