### ISSUE TITLE
Why do I use Chinese in the @module, the method below the module cannot be opened in the page

### ISSUE THREAD

**Issue by bubble1001** [clenemt/docdash#118]
I used the Chinese in @module, so in the generated document page, when I click the function name under the Chinese name, the page displays "Your file couldn't be accessed", it seems that the url has been used 'encodedURI()' many times

**Comment by ar2rsawseen** [comment]
Hello,
can you provide small example to reproduce?

**Comment by bubble1001** [comment]
My usage is like this:

/**@module 加法 */

/**
* @function add
* @param {number} a - 第一个参数
* @param {number} b - 第二个参数
* @returns {number} - 返回两个参数的和
*/
function add(a, b) {
    return a + b;
}

In the final generated document page, click the add() method under the document directory "加法", and the page prompts "Your file couldn't be accessed"
![image](https://github.com/clenemt/docdash/assets/45547172/f2b797dd-26ad-4c8d-9bae-9ed1d29e3ef1)

**Comment by ar2rsawseen** [comment]
Hello,
thank you, I could track it to JSDoc place here:
https://github.com/jsdoc/jsdoc/blob/main/packages/jsdoc-template-legacy/lib/templateHelper.js#L351

So, most probably, it is not a template problem but JSDoc problem in overall.

Have you experienced the same with the default JSDoc template?

**Comment by ar2rsawseen** [comment]
So for example, as far as I see
here https://github.com/clenemt/docdash/blob/master/publish.js#L386
we feed method.longname as `module:加法~add`
and get result as `<a href="module-%2525E5%25258A%2525A0%2525E6%2525B3%252595.html#~add">add</a>`

**Comment by bubble1001** [comment]
Thanks for your reply, but I don't have same problem when I use other templates. And after I fix it like this, the above problem will not occur again. https://github.com/clenemt/docdash/pull/119,
