### ISSUE TITLE
Display member

### ISSUE THREAD

**Issue by rain1024** [clenemt/docdash#13]
Hi docdash team.

First of all, I'm very happy to use your awesome template for my javascript project. Thank you so much for doing docdash.

I have a question. Is it possible to display member of class in table of content?

**Comment by clenemt** [comment]
Yes it should be possible through an option.
Will look into that when i have time :+1:

**Comment by jedahu** [comment]
Any movement on this?

**Comment by ar2rsawseen** [comment]
Added in https://github.com/clenemt/docdash/pull/20
