### ISSUE TITLE
Links in extended classes

### ISSUE THREAD

**Issue by arracso** [clenemt/docdash#25]
Hi, first of all I really like how docdash looks and how it organizes the classes and modules.

JSDOC 3 link extended classes so you can click to see the parent class. I think this linkage is very important.

I don't see any issue openen or closed since a while. Is this project abandoned?

**Comment by ar2rsawseen** [comment]
Hello,
I see such link for extends, can you provide an example, where you don't see a link?
Maybe it was added later?

**Comment by ar2rsawseen** [comment]
By adding comment:

```
* @extends MyOtherClass
```

link appears correctly, if you have more input, please reopen ticket
