### ISSUE TITLE
See tags not linking properly

### ISSUE THREAD

**Issue by danvim** [clenemt/docdash#31]
See tags aren't linked and the resulting corresponding html code contains no `<a>`. Probably because in the `details.tmpl`:

```
<?js if (data.see && see.length) {?>
  <dt class="tag-see">See:</dt>
  <dd class="tag-see">
    <ul><?js see.forEach(function(s) { ?>
      <li><?js= self.linkto(s) ?></li>
    <?js }); ?></ul>
  </dd>
<?js } ?>
```

`self.linkto(s)` would not produce a link, because `s` is not a URL?

**Comment by ar2rsawseen** [comment]
Linkto actually outputs link, if it links to another file
https://github.com/jsdoc3/jsdoc/blob/master/lib/jsdoc/util/templateHelper.js#L355

so maybe what you provide is not correct, you should probably use namepath

Please reopen if issue still persists and provide an example
