### ISSUE TITLE
autodetect structure - i.e. classes and methods

### ISSUE THREAD

**Issue by giorgiobeggiora** [clenemt/docdash#32]
Is there a way to autodetect the structure as documentation.js does (without using @class, @method and @memberof), or is there a way to make this theme work with documentation.js ?

Thanks

example: 
```
/**
 * my product class
 */
class Product () {
  /**
   * my 1st method
   */
  method1 () {}
  /**
   * my 2nd method
   */
  method2 () {}
}

```
expected documentation's left bar:

**CLASSES**
Product
| method1
| method2

thanks.

**Comment by ar2rsawseen** [comment]
Unfortunately I feel that is not part of the template's job, but rather JSDoc job itself, you can try opening such ticket there
