### ISSUE TITLE
Tables have display issues in docdash

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [clenemt/docdash#33]
Background
-------------
I have a table that displays information about a given algorithm. I expected the table to have divisions and the columns to be respected. This does not seem to happen. 

Code
--------

Following is an example using bubble sort.

```
/**
 * @namespace Quadratic.bubble
 * @desc
 * Some description about bubble sort here
 *
 * | Sort Type       | Best-case perf. | Worst-case perf.  | Average perf. | Worst-case space perf.  | Stable  |
 * | :-------------- | :-------------- | :---------------  | :------------ | :---------------------  | :-----  |
 * | Comparison Sort | O(n)            | O(nˆ2)            | O(nˆ2)        | O(1) aux                | Yes     |
 *
 * .... more stuff
 */
```

As you can see, this is a markdown table. 

Problem
------

This is what the page displays:

![-home-pedro-workspace-node-sortable-docs-quadratic bubble html](https://user-images.githubusercontent.com/2980392/34463729-b218a0d4-ee65-11e7-8920-49ab34e63e5b.png)

As you can see the table has no divisions whatsoever. It is also not clear where a given column begins and ends. 

Converting the code to HTML has no difference ( as expected ). 

Question
---------

 - Is there a way to make docdash display tables with divisions?
 - If not, is there a better way to display tables in docdash that I am not aware of?
 - If not, what format would you use to display the table's information?

**Comment by ar2rsawseen** [comment]
It looks like table is kind of supported, but mostly looks like CSS issue, so would be needed to fix styles for table.
Any one up for such PR?

**Comment by ar2rsawseen** [comment]
Added some global table styles in:
https://github.com/clenemt/docdash/commit/0f746a86e13774c152c08c4c81d0f2a4113540c0

And it looks like this:
![image](https://user-images.githubusercontent.com/399992/44144609-d9f3c61e-a090-11e8-9a13-45247f88f2f0.png)

But as I am not a designer, if someone can do a better job, PR is welcome :)
