### ISSUE TITLE
Support for useLongnameInNav

### ISSUE THREAD

**Issue by radarfox** [clenemt/docdash#39]
Hello,

I'm missing support for configuration option `templates.default.useLongnameInNav` ([JSDoc documentation](http://usejsdoc.org/about-configuring-default-template.html#showing-longnames-in-the-navigation-column)).

For example, there are two classes `Foo` and `Bar`. If I define that `Bar` is `@memberof Foo`, then the `Bar` class heading if correctly showing `Foo.Bar`. But in the nav bar there is only `Bar` shown despite being sorted as if it had name `Foo.Bar` (i will output `Bar` item just after `Foo`).

**Comment by ar2rsawseen** [comment]
Added support for it here:
https://github.com/clenemt/docdash/commit/3f9ad3bf7479b8f5c5d1128859d915ded4aec7fb
