### ISSUE TITLE
publish creates sub-folders for everything static

### ISSUE THREAD

**Issue by evantahler** [clenemt/docdash#42]
Now, when you publish, static assets end up in sub folders.  This means the template cannot load files properly.

Expected: `scripts/prettify/prettify.js`
Actual: `scripts/prettify/prettify.js/prettify.js`

**Comment by ar2rsawseen** [comment]
Hello,
what is your OS and nodejs version?
I seem to have such problem on Windows, but on Linux all works correctly. 
Just trying to gather more info on what it depends

**Comment by ar2rsawseen** [comment]
Ok, it seems to be a bug with copyFileSync specifically, copyFile works normally, so changed to that and it seems to fix it:
https://github.com/clenemt/docdash/commit/8e77ad80a5e208cc15cae718c0f2119916963a12
