### ISSUE TITLE
npm package is still on version 0.4.0

### ISSUE THREAD

**Issue by mayfield** [clenemt/docdash#43]
Looks like you've been actively developing but the npm package is 2 years old.  Is it time for a publish?

**Comment by ar2rsawseen** [comment]
yep, you are right, was doing last checks on weekend all seems to be working, will publish soon, just can't decide if we really should go with 1.0.0 or bump to 0.5.0

**Comment by mayfield** [comment]
Thanks!

**Comment by ar2rsawseen** [comment]
Published 1.0.0
