### ISSUE TITLE
link in extends tag is invaild, when baseclass include memberof tag

### ISSUE THREAD

**Issue by DerekMar** [clenemt/docdash#45]

**Comment by DerekMar** [comment]
![image](https://user-images.githubusercontent.com/20637828/45604253-203afc80-ba65-11e8-86f4-b6ba2e6b2cb7.png)
![image](https://user-images.githubusercontent.com/20637828/45604273-511b3180-ba65-11e8-940e-7d043ad99005.png)

A class extends B class，but the Extends‘s link is invalid.

![image](https://user-images.githubusercontent.com/20637828/45604259-27faa100-ba65-11e8-910e-fc8cf56ffb53.png)
Once I add memberof tag in the baseclass, the link will be invalid

**Comment by DerekMar** [comment]
![image](https://user-images.githubusercontent.com/20637828/45604339-f3d3b000-ba65-11e8-9d5a-13173ca99328.png)

the whole code

**Comment by ar2rsawseen** [comment]
Hello,
if link on the extends does not appear, in most cases it means you provided incorrect namepath.
so if you use
```
@extends control
```
some where namepath control must be defined. The fact that putting memberof to base class makes it work, means JSDoc does not pick up that namepath by its own.

Either way, this seems to be more of JSDoc issue than template.

Please try to reproduce the same with vanila JSDoc, and if it works there, then please reopen the ticket and we can dive deeper here to check if there were some changes that might break that.
