### ISSUE TITLE
Wrap clipped text

### ISSUE THREAD

**Issue by briank621** [clenemt/docdash#48]
When the module name is too long, the name of the file is clipped. Is it possible to have it wrap around to the next line?

![screen shot 2018-12-19 at 10 50 50 am](https://user-images.githubusercontent.com/9010681/50231196-3ca84700-037c-11e9-8145-beedf29e2085.png)

**Comment by ar2rsawseen** [comment]
Fixed here:
https://github.com/clenemt/docdash/commit/a2a9848c1bf581607fad3ebeb2eee99b4ed6cce2

Will release asap
