### ISSUE TITLE
Clipped text on iPhone 8 and iPhone X

### ISSUE THREAD

**Issue by RandomByte** [clenemt/docdash#50]
Opening the [demo](http://clenemt.github.io/docdash/) page on an iPhone 8 or iPhone X (probably also on others) leads to clipped text rendering.

In Safari on iPhone X it looks like this:

![img_3359](https://user-images.githubusercontent.com/1589939/50637684-42e11a80-0f5b-11e9-85a9-60b22d7ecdff.PNG)
![img_3360](https://user-images.githubusercontent.com/1589939/50637409-3ad4ab00-0f5a-11e9-8041-7a8aa964d95c.PNG)

This can also be reproduced in Chrome by simulating an iPhone X via DevTools -> "Toggle device toolbar" (in the upper left corner) -> iPhone X -> Open http://clenemt.github.io/docdash/

**Comment by ar2rsawseen** [comment]
Fixed here:
https://github.com/clenemt/docdash/commit/9a7d8725e8d81a9f6474f9e52a947d1e5471e167
Will be in next release. Try to release it once a month and just did a release today :)
