### ISSUE TITLE
Including `version` from `package.json` in template

### ISSUE THREAD

**Issue by juanpaco** [clenemt/docdash#55]
Just a question, the default jsdoc template includes a package's version on the home page.  Would you be open to a PR adding that to the docdash template?

**Comment by ar2rsawseen** [comment]
You mean JSDoc package version?
or docdash package version?

Eitherway, I guess for reporting problems, it would be good to show them, especially JSDoc, as we just load the latest in package.json, and it is possible users have not upgraded lately.

**Comment by juanpaco** [comment]
Sorry for the delay!  I mean the version of the thing that I'm documenting.  The default jsdoc template does that with this block: https://github.com/jsdoc3/jsdoc/blob/master/templates/default/tmpl/mainpage.tmpl#L6

**Comment by ar2rsawseen** [comment]
Added it here:
https://github.com/clenemt/docdash/commit/a12fa912e452a8c8651a543c4a44c914f0751e7a

Will release soon

**Comment by juanpaco** [comment]
Thank you so much for getting this in.  Sorry I didn't get to the PR.

**Comment by ar2rsawseen** [comment]
No problem 😃
