### ISSUE TITLE
Support generators (@yields)

### ISSUE THREAD

**Issue by towerofnix** [clenemt/docdash#56]
JSDoc supports use of the `@generator` and `@yields` tags to support documentation for [generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*#Description). The `@generator` tag is already (sort-of) understood by docdash, but the `@yields` tag is not.

![An example function signature outputted from docdash: "(async, generator) getFollowing()"](https://user-images.githubusercontent.com/9948030/51949815-78670f80-2404-11e9-842e-f831395f9ad8.png)

In order to properly support documenting generators, support for the `@yields` tag should be added.

I suggest treating it very similarly to a `@returns` tag; the above example would say, for example, `(async, generator) getFollowing() → {string}`, and below the method description, there would be a "Returns: Type - String" section.

**Comment by ar2rsawseen** [comment]
Added it here: https://github.com/clenemt/docdash/commit/a12fa912e452a8c8651a543c4a44c914f0751e7a
Will release soon
