### ISSUE TITLE
Getter/Setters in Navigation

### ISSUE THREAD

**Issue by chasse20** [clenemt/docdash#58]
Hi, great plugin!

I think one missing feature I'd love to see is an option to toggle those es6 get/set properties to be visible in the side nav. Or is this something that jsdoc will have to implement for you to parse?

Thank you!

**Comment by ar2rsawseen** [comment]
Hello,
can you provide an example code and comment and anything you can that would generate them? It would allow me to get the feature done much faster, when I get free time :)

**Comment by ar2rsawseen** [comment]
Closing as no additional info
