### ISSUE TITLE
IE 11: Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by vago** [clenemt/docdash#61]
With the removal of jquery in the latest version, the search no longer works in IE11. When trying to search, it gives above error in console.

The problem occures in `search.js#contains()` method, 

`return (a.textContent || a.innerText || "").toUpperCase().includes(m)`

**Comment by ar2rsawseen** [comment]
Issue fixed here: https://github.com/clenemt/docdash/commit/f20864a8d3daf1d73778fccad176b3ec4ba00442
And released 1.1.1

**Comment by vago** [comment]
Great, thanks for super quick fix and release!
