### ISSUE TITLE
Source code view removes empty lines

### ISSUE THREAD

**Issue by rugk** [clenemt/docdash#67]
When you have empty lines in your source code, they are removed from the source code view in the template.

Linux

**Comment by ar2rsawseen** [comment]
Can you provide an example for this or screenshot on what exactly do you mean?

**Comment by rugk** [comment]
In your own example, I guess:
https://clenemt.github.io/docdash/mixins_signalable.js.html

![image](https://user-images.githubusercontent.com/11966684/61483746-c31e1900-a99d-11e9-925c-51a5ceb777a2.png)

There are likely empty lines in there.

**Comment by ar2rsawseen** [comment]
Not what I see 😄 
![image](https://user-images.githubusercontent.com/399992/61487838-80fdd300-a9af-11e9-9cdb-ed01b1507de2.png)

Which browser do you use?

**Comment by rugk** [comment]
Firefox 68

**Comment by rugk** [comment]
The issue seems to be that the empy line seems to have no space and the element takes up no height:
![grafik](https://user-images.githubusercontent.com/11966684/61527179-26e72700-aa1c-11e9-86a0-f64526421e05.png)

**Comment by ar2rsawseen** [comment]
This should be fixed here:
https://github.com/clenemt/docdash/commit/5e99ca0bb36dc3535ac3803782c4275c97768552

**Comment by rugk** [comment]
So why not close this issue then now?

**Comment by ar2rsawseen** [comment]
Will do when release is made with the fix :)
So if someone is searching for the resolution to the same problem, they can find it here
but when release is made, the fix will already be out there :)
