### ISSUE TITLE
Turn on linenums

### ISSUE THREAD

**Issue by fedemengo** [clenemt/docdash#68]
I was following the docs for configuring docdash with jsdoc but the link that specify how to turn on line number is not working

> - linenums
When true, line numbers will appear in the source code listing. If you have
also [turned that on](http://usejsdoc.org/about-configuring-jsdoc.html).

The website seems to be down

**Comment by ar2rsawseen** [comment]
Where did you find that link exactly?
New domain is https://jsdoc.app/about-configuring-jsdoc.html

**Comment by ar2rsawseen** [comment]
Could not find it anywhere in the docs, but either way, they are redirecting old domain to new one now, so it should not be a problem anymore
