### ISSUE TITLE
Font - dependency on fonts.googleapis.com

### ISSUE THREAD

**Issue by atcol** [clenemt/docdash#70]
Access to fonts.googleapis.com is blocked by the firewall where my generated jsdoc is accessed. Is there a way of replacing or dropping this dependency entirely? At the moment because the hostname cannot resolve the page loads take over 20 seconds.

**Comment by ar2rsawseen** [comment]
Yes, there is a pull request for this, so we will definitely do that, but not yet sure, when exactly I will have time to get on to it :)

**Comment by atcol** [comment]
OK, for now I'll do a simple sed: `sed -i 's/@import.*//' $PATH`.

Thanks for the really nice theme!

**Comment by ar2rsawseen** [comment]
have been merged here:
https://github.com/clenemt/docdash/pull/63

and improved here:
https://github.com/clenemt/docdash/commit/5476db4245d68cc1ab01ce29c88b6bdbf636cfa5
