### ISSUE TITLE
config for theme / accent color?

### ISSUE THREAD

**Issue by crobinson42** [clenemt/docdash#76]
I was wondering if docdash has the option or would accept a PR to config the theme accent color?

**Comment by ar2rsawseen** [comment]
Hello,
you can just inject your own CSS file overwriting default colors and other styles to achieve your own "theme" :)

In your config just provide something like (relative to static folder):
```
"scripts": ["./styles/theme-green.css"],
```

**Comment by crobinson42** [comment]
Ah! Thanks - sometimes you totally overlook such a simple solution ;-)
