### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by stfxz** [clenemt/docdash#79]
hello, recently I used the docdash template in my documentation with JSDoc (and I really liked it, congratulations!), but I wanted to know how I TOTALLY change the background color, I already tried to change everything I found, however, it is not right, there are several white parts. Thank you for your attention, and congratulations!

**Comment by ar2rsawseen** [comment]
Hello,
you can inject your custom CSS files like discussed here: https://github.com/clenemt/docdash/issues/76
and overwrite any styles you want

if you override background and there are still white parts, you just have to override them too, one by one

**Comment by stfxz** [comment]
Ok, thanks, have a good day
