### ISSUE TITLE
Add home page sections to navbar?

### ISSUE THREAD

**Issue by philipmjohnson** [clenemt/docdash#8]
I just started using docdash after reviewing a few themes for JsDoc and think it's the best one out there. Here's my site:

http://radgrad.org/datamodel/

and the underlying repo:

https://github.com/radgrad/datamodel

I'm not sure how hard this would be, but one significant improvement to my documentation would be to create a way to add sections in the home page (in my case, my README.md) to the navbar. So, instead of just "Home", the navbar would contain:

Home
  Overview
  Development procedures and scripts
  ...

There are TOC packages for markdown, so maybe it wouldn't be too bad.

Thanks for your consideration, and thanks for releasing such a nice package to the community.

**Comment by ar2rsawseen** [comment]
Added allowing custom menu items:
https://github.com/clenemt/docdash/commit/f4f7c874fbe9bb46788d3759ffd977e2d2ec575f
