### ISSUE TITLE
Ignore carriage returns in jsdoc comment sections?

### ISSUE THREAD

**Issue by philipmjohnson** [clenemt/docdash#9]
I use ESLint which enforces a hard limit of 120 characters on line width.  The generated documentation replicates the exact line widths in my source code, which is suboptimal (for example, on mobile there is a lot of superfluous wrapping, and on large monitors the available width is not used.)

Is there a way to ignore the carriage returns when generating the HTML? 

Thanks!

**Comment by clenemt** [comment]
You could easily make a plugin for that. Take a look at my [no-star](https://github.com/clenemt/no-star-example) plugin for example. It removes whitespace when not using `*` with comments.

You could do something very similar for your carriage return.

Thanks for using this theme :+1:
