### ISSUE TITLE
(wish) Collapse section

### ISSUE THREAD

**Issue by ivmartel** [clenemt/docdash#92]
It would be nice to be able to collapse sections for the case of projects with large number of classes/namespace/...
Version 1.2 allows to collapse object members but no the top section (namespace, events, classes...)

**Comment by ankit-kumar-kr** [comment]
try [clean-jsdoc-theme](https://www.npmjs.com/package/clean-jsdoc-theme) they have that feature.

**Comment by ivmartel** [comment]
I'm talking about collapsing the main sections (classes, modules, externals). I added issue [62](https://github.com/ankitskvmdam/clean-jsdoc-theme/issues/62) to do the same in `clean-jsdoc-theme`.
