### ISSUE TITLE
Use of @hideconstructor with virtual classes creates an empty page

### ISSUE THREAD

**Issue by CMR-DEV** [clenemt/docdash#94]
I'm using docdash `1.2.0` to document virtual classes for an external module to give a quick reference to the offical docs with `@see` like this:
```
/**
 * The module instance of Three.js
 * 
 * @namespace module:Viewer.THREE
 * @see {@link https://threejs.org/|Three.js}
*/

/** 
 * Lorem Ipsum
 * 
 * @class DirectionalLight
 * @memberof module:Viewer.THREE
 * @hideconstructor
 * @see {@link https://threejs.org/docs/#api/en/lights/DirectionalLight|DirectionalLight}
*/

/** 
 * @class HemisphereLight
 * @memberof module:Viewer.THREE
 * @hideconstructor
 * @see {@link https://threejs.org/docs/#api/en/lights/HemisphereLight|HemisphereLight}
*/
```
However this results in an empty page for each class (even for the one with the description):
![DirectionalLight output page](https://user-images.githubusercontent.com/65172002/102695695-442fae80-4229-11eb-9f7c-7efca3a5638a.png)

When I remove the `@hideconstructor` tag everything is built as expected, but I don't want the constructor in my docs I just want to reference the offical docs of theese classes. In the JSDoc's default template however the `@see` reference is drawn even when `@hideconstructor` is present. So I don't think this behaviour is intended.

**Comment by ar2rsawseen** [comment]
Hello,
the problem is that see link is attached to some method or other entity and the only entity here is the constructor, and if you hide it, there are no more entities display, thus empty page.
I am not sure what other entity you could attach it too
