### ISSUE TITLE
Add class to <h5>Parameters</h5> and other h5 elements

### ISSUE THREAD

**Issue by hugolpz** [clenemt/docdash#97]
I would like to custom css for some large titles in order to reduce [Chartjunk](https://en.wikipedia.org/wiki/Chartjunk) : _"redundant pixels with no additional information"_.

To allows easier customisations via css, it would be better of we have something such as :
* `<h5>Parameters:</h5>`  -> `<h5 class="h5-parameters">Parameters:</h5>`
* `<h5>Returns:</h5>`  -> `<h5 class="h5-returns">Returns</h5>`

![Screenshot_2021-03-31_11-32-49](https://user-images.githubusercontent.com/1420189/113123405-d9711480-9214-11eb-8fff-389170117ecf.png)
![Screenshot_2021-03-31_11-36-42](https://user-images.githubusercontent.com/1420189/113124017-61571e80-9215-11eb-89f5-2ccea82091c7.png)

See also : https://github.com/clenemt/docdash/issues/19

**Comment by ar2rsawseen** [comment]
Added here: https://github.com/clenemt/docdash/commit/90f527fcc6906a166d103a228fe7e34c5e9b4640

**Comment by hugolpz** [comment]
@ar2rsawseen thank you ! that what was needed !
